http:
 listner:
   host: "localhost"
   port: "8083"
 requester:
   host: "localhost"
   port: "8082"
   path: "/api/accounts"
   
smtp:
  host: "Smtp.gmail.com"
  port: "587"
  user: "lakkyreddyvamsi@gmail.com"
  
